# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'CodingTest_Meteo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!

  pod 'Hero'
  pod 'RxSwift'
  pod 'RxSwiftExt'
  pod 'R.swift'

  target 'CodingTest_MeteoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
